version: "3.8"

services:
  api:
    build: .
    ports:
      - "4444:4444"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
      SECRET_KEY: 123456
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_IN_MINUTES: 30
    restart: always
  
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
    volumes:
      - "./sql_data:/var/lib/postgressql/data"